import type {
  DynamicBattleType,
  ScenarioName,
  UnitType,
} from "@lob-sdk/types";
import { STAT_PRECISION_SCALE } from "./scale";

/**
 * Raw shape of `game-constants.json` (unscaled, human-readable).
 * The {@link GameConstants} class implements this interface and scales the
 * stat-coupled constants on construction.
 */
export interface GameConstantsJson {
  TICKS_PER_TURN: number;
  COLLISION_DETECTION_SUBTICKS: number;
  COLLISION_CHECK_RADIUS: number;
  COLLISION_PUSH_MAX_ANGLE_RANGE_DEGREES: number;
  UNIT_RANGE_MARGIN: number;
  TILE_SIZE: number;
  MAX_RANKED_GAME_TURNS: number;
  MIN_CUSTOM_GAME_MAX_TURNS: number;
  MAX_CUSTOM_GAME_MAX_TURNS: number;
  MIN_OFFLINE_GAME_MAX_TURNS: number;
  MAX_OFFLINE_GAME_MAX_TURNS: number;
  MAX_INACTIVE_TURNS: number;
  ROUT_THRESHOLD_TURNS: number;
  ROUTING_COLLISION_LEVEL: number;
  DEFAULT_MAP_WIDTH: number;
  DEFAULT_MAP_HEIGHT: number;
  DEFAULT_DEPLOYMENT_ZONE_WIDTH: number;
  DEFAULT_DEPLOYMENT_ZONE_HEIGHT: number;
  DEFAULT_DEPLOYMENT_ZONE_SEPARATION: number;
  MAX_PLAYERS: number;
  MIN_FOLLOW_ALLY_DISTANCE_SQUARED: number;
  ALLY_HARD_COLLISION_THRESHOLD: number;
  MOVEMENT_PATH_POINT_PROXIMITY_THRESHOLD_SQUARED: number;
  MOVEMENT_PATH_FINAL_POINT_PROXIMITY_THRESHOLD_SQUARED: number;
  MOVEMENT_PATH_ROTATION_SIMILARITY_THRESHOLD: number;
  MOVEMENT_PATH_FINAL_POINT_ROTATION_SIMILARITY_THRESHOLD: number;
  FOLLOW_ROTATION_THRESHOLD: number;
  CAN_LEAVE_MAP_MIN_ORG: number;
  CAN_LEAVE_MAP_MIN_HP_PROPORTION: number;
  /** Full attack cycle in ticks — unit attacks once every ATTACK_PERIOD ticks. */
  ATTACK_PERIOD: number;
  CHARGE_RESISTANCE_LOSS_BY_ORG: number;
  MAX_HP_RANGED_ATTACK_PENALTY: number;
  MAX_HP_MELEE_ATTACK_BONUS: number;
  MAX_HP_MELEE_ATTACK_PENALTY: number;
  MAX_DAMAGE_MODIFIER_CLAMP: number;
  NEARBY_UNITS_DISTANCE: number;
  NEARBY_UNITS_CHARGE_RESISTANCE_MODIFIER_CAP: number;
  NEARBY_UNITS_CHARGE_RESISTANCE_MODIFIER_PENALTY_CAP: number;
  NEARBY_UNITS_CHARGE_PENETRATION_MODIFIER_CAP: number;
  NEARBY_UNITS_CHARGE_PENETRATION_MODIFIER_PENALTY_CAP: number;
  MIN_EFFECTIVE_VPS: number;
  SHOT_TRAJECTORY_TARGET_ALTITUDE: number;
  OFFER_DRAW_COOLDOWN: number;
  MAX_ENTITY_NAME_LENGTH: number;
  CHARGE_BACKLASH_RESIST_MOD: number;
  CHARGE_BACKLASH_MAX_REDUCTION: number;
  CHARGE_BACKLASH_DEFENDER_CHARGE_BONUS_MULTIPLIER: number;
  CHARGE_BACKLASH_DEFENDER_RESISTANCE_MULTIPLIER: number;
  HAS_TAKEN_FIRE_SPEED_MODIFIER: number;
  EFFECT_HAS_RAN_TICKS: number;
  EFFECT_STARTED_ROUTING_TICKS: number;
  HEAD_ON_COLLISION_ANGLE_DEGREES: number;
  HEIGHT_CHANGE_STAMINA_COST: number;
  HEIGHT_CHANGE_TICKS: number;
  HEIGHT_CHANGE_RUNNING_STAMINA_COST: number;
  WALKING_STAMINA_REGAIN_MODIFIER: number;
  FORWARD_DEPLOYMENT_ZONE_OFFSET: number;
  FOW_EYE_HEIGHT: number;
  FOW_TARGET_HEIGHT: number;
  FOW_LEVEL_0_DISTANCE: number;
  FOW_LEVEL_1_DISTANCE: number;
  FOW_LEVEL_2_DISTANCE: number;
  FOW_LEVEL_3_DISTANCE: number;
  VP_BASE_POINTS: number;
  VP_LOSS_RATIO_POINTS: number;
  VP_POINTS_TO_TIE_BREAK: number;
  VP_BIG_DEFAULT_POINTS: number;
  VP_SMALL_DEFAULT_POINTS: number;
  VP_TICKS_UNDER_PRESSURE_BASE: number;
  PLAYER_EXPERIENCE_BASE: number;
  PLAYER_EXPERIENCE_FACTOR: number;
  INITIAL_ELO: number;
  UNKNOWN_UNIT_TYPE: UnitType;
  DEFAULT_SCENARIO: ScenarioName;
  DEFAULT_BATTLE_TYPE: DynamicBattleType;
  ROUTING_FORMATION: string;
  BETA: boolean;
}

/**
 * Runtime view of game constants: same shape as the JSON with the few
 * stat-coupled constants (org thresholds, height-change stamina costs)
 * multiplied by {@link STAT_PRECISION_SCALE}.
 */
export class GameConstants implements GameConstantsJson {
  TICKS_PER_TURN: number;
  COLLISION_DETECTION_SUBTICKS: number;
  COLLISION_CHECK_RADIUS: number;
  COLLISION_PUSH_MAX_ANGLE_RANGE_DEGREES: number;
  UNIT_RANGE_MARGIN: number;
  TILE_SIZE: number;
  MAX_RANKED_GAME_TURNS: number;
  MIN_CUSTOM_GAME_MAX_TURNS: number;
  MAX_CUSTOM_GAME_MAX_TURNS: number;
  MIN_OFFLINE_GAME_MAX_TURNS: number;
  MAX_OFFLINE_GAME_MAX_TURNS: number;
  MAX_INACTIVE_TURNS: number;
  ROUT_THRESHOLD_TURNS: number;
  ROUTING_COLLISION_LEVEL: number;
  DEFAULT_MAP_WIDTH: number;
  DEFAULT_MAP_HEIGHT: number;
  DEFAULT_DEPLOYMENT_ZONE_WIDTH: number;
  DEFAULT_DEPLOYMENT_ZONE_HEIGHT: number;
  DEFAULT_DEPLOYMENT_ZONE_SEPARATION: number;
  MAX_PLAYERS: number;
  MIN_FOLLOW_ALLY_DISTANCE_SQUARED: number;
  ALLY_HARD_COLLISION_THRESHOLD: number;
  MOVEMENT_PATH_POINT_PROXIMITY_THRESHOLD_SQUARED: number;
  MOVEMENT_PATH_FINAL_POINT_PROXIMITY_THRESHOLD_SQUARED: number;
  MOVEMENT_PATH_ROTATION_SIMILARITY_THRESHOLD: number;
  MOVEMENT_PATH_FINAL_POINT_ROTATION_SIMILARITY_THRESHOLD: number;
  FOLLOW_ROTATION_THRESHOLD: number;
  CAN_LEAVE_MAP_MIN_ORG: number;
  CAN_LEAVE_MAP_MIN_HP_PROPORTION: number;
  ATTACK_PERIOD: number;
  CHARGE_RESISTANCE_LOSS_BY_ORG: number;
  MAX_HP_RANGED_ATTACK_PENALTY: number;
  MAX_HP_MELEE_ATTACK_BONUS: number;
  MAX_HP_MELEE_ATTACK_PENALTY: number;
  MAX_DAMAGE_MODIFIER_CLAMP: number;
  NEARBY_UNITS_DISTANCE: number;
  NEARBY_UNITS_CHARGE_RESISTANCE_MODIFIER_CAP: number;
  NEARBY_UNITS_CHARGE_RESISTANCE_MODIFIER_PENALTY_CAP: number;
  NEARBY_UNITS_CHARGE_PENETRATION_MODIFIER_CAP: number;
  NEARBY_UNITS_CHARGE_PENETRATION_MODIFIER_PENALTY_CAP: number;
  MIN_EFFECTIVE_VPS: number;
  SHOT_TRAJECTORY_TARGET_ALTITUDE: number;
  OFFER_DRAW_COOLDOWN: number;
  MAX_ENTITY_NAME_LENGTH: number;
  CHARGE_BACKLASH_RESIST_MOD: number;
  CHARGE_BACKLASH_MAX_REDUCTION: number;
  CHARGE_BACKLASH_DEFENDER_CHARGE_BONUS_MULTIPLIER: number;
  CHARGE_BACKLASH_DEFENDER_RESISTANCE_MULTIPLIER: number;
  HAS_TAKEN_FIRE_SPEED_MODIFIER: number;
  EFFECT_HAS_RAN_TICKS: number;
  EFFECT_STARTED_ROUTING_TICKS: number;
  HEAD_ON_COLLISION_ANGLE_DEGREES: number;
  HEIGHT_CHANGE_STAMINA_COST: number;
  HEIGHT_CHANGE_TICKS: number;
  HEIGHT_CHANGE_RUNNING_STAMINA_COST: number;
  WALKING_STAMINA_REGAIN_MODIFIER: number;
  FORWARD_DEPLOYMENT_ZONE_OFFSET: number;
  FOW_EYE_HEIGHT: number;
  FOW_TARGET_HEIGHT: number;
  FOW_LEVEL_0_DISTANCE: number;
  FOW_LEVEL_1_DISTANCE: number;
  FOW_LEVEL_2_DISTANCE: number;
  FOW_LEVEL_3_DISTANCE: number;
  VP_BASE_POINTS: number;
  VP_LOSS_RATIO_POINTS: number;
  VP_POINTS_TO_TIE_BREAK: number;
  VP_BIG_DEFAULT_POINTS: number;
  VP_SMALL_DEFAULT_POINTS: number;
  VP_TICKS_UNDER_PRESSURE_BASE: number;
  PLAYER_EXPERIENCE_BASE: number;
  PLAYER_EXPERIENCE_FACTOR: number;
  INITIAL_ELO: number;
  UNKNOWN_UNIT_TYPE: UnitType;
  DEFAULT_SCENARIO: ScenarioName;
  DEFAULT_BATTLE_TYPE: DynamicBattleType;
  ROUTING_FORMATION: string;
  BETA: boolean;

  constructor(json: GameConstantsJson) {
    this.TICKS_PER_TURN = json.TICKS_PER_TURN;
    this.COLLISION_DETECTION_SUBTICKS = json.COLLISION_DETECTION_SUBTICKS;
    this.COLLISION_CHECK_RADIUS = json.COLLISION_CHECK_RADIUS;
    this.COLLISION_PUSH_MAX_ANGLE_RANGE_DEGREES =
      json.COLLISION_PUSH_MAX_ANGLE_RANGE_DEGREES;
    this.UNIT_RANGE_MARGIN = json.UNIT_RANGE_MARGIN;
    this.TILE_SIZE = json.TILE_SIZE;
    this.MAX_RANKED_GAME_TURNS = json.MAX_RANKED_GAME_TURNS;
    this.MIN_CUSTOM_GAME_MAX_TURNS = json.MIN_CUSTOM_GAME_MAX_TURNS;
    this.MAX_CUSTOM_GAME_MAX_TURNS = json.MAX_CUSTOM_GAME_MAX_TURNS;
    this.MIN_OFFLINE_GAME_MAX_TURNS = json.MIN_OFFLINE_GAME_MAX_TURNS;
    this.MAX_OFFLINE_GAME_MAX_TURNS = json.MAX_OFFLINE_GAME_MAX_TURNS;
    this.MAX_INACTIVE_TURNS = json.MAX_INACTIVE_TURNS;
    this.ROUT_THRESHOLD_TURNS = json.ROUT_THRESHOLD_TURNS;
    this.ROUTING_COLLISION_LEVEL = json.ROUTING_COLLISION_LEVEL;
    this.DEFAULT_MAP_WIDTH = json.DEFAULT_MAP_WIDTH;
    this.DEFAULT_MAP_HEIGHT = json.DEFAULT_MAP_HEIGHT;
    this.DEFAULT_DEPLOYMENT_ZONE_WIDTH = json.DEFAULT_DEPLOYMENT_ZONE_WIDTH;
    this.DEFAULT_DEPLOYMENT_ZONE_HEIGHT = json.DEFAULT_DEPLOYMENT_ZONE_HEIGHT;
    this.DEFAULT_DEPLOYMENT_ZONE_SEPARATION =
      json.DEFAULT_DEPLOYMENT_ZONE_SEPARATION;
    this.MAX_PLAYERS = json.MAX_PLAYERS;
    this.MIN_FOLLOW_ALLY_DISTANCE_SQUARED =
      json.MIN_FOLLOW_ALLY_DISTANCE_SQUARED;
    this.ALLY_HARD_COLLISION_THRESHOLD = json.ALLY_HARD_COLLISION_THRESHOLD;
    this.MOVEMENT_PATH_POINT_PROXIMITY_THRESHOLD_SQUARED =
      json.MOVEMENT_PATH_POINT_PROXIMITY_THRESHOLD_SQUARED;
    this.MOVEMENT_PATH_FINAL_POINT_PROXIMITY_THRESHOLD_SQUARED =
      json.MOVEMENT_PATH_FINAL_POINT_PROXIMITY_THRESHOLD_SQUARED;
    this.MOVEMENT_PATH_ROTATION_SIMILARITY_THRESHOLD =
      json.MOVEMENT_PATH_ROTATION_SIMILARITY_THRESHOLD;
    this.MOVEMENT_PATH_FINAL_POINT_ROTATION_SIMILARITY_THRESHOLD =
      json.MOVEMENT_PATH_FINAL_POINT_ROTATION_SIMILARITY_THRESHOLD;
    this.FOLLOW_ROTATION_THRESHOLD = json.FOLLOW_ROTATION_THRESHOLD;
    this.CAN_LEAVE_MAP_MIN_HP_PROPORTION = json.CAN_LEAVE_MAP_MIN_HP_PROPORTION;
    this.ATTACK_PERIOD = json.ATTACK_PERIOD;
    this.CHARGE_RESISTANCE_LOSS_BY_ORG = json.CHARGE_RESISTANCE_LOSS_BY_ORG;
    this.MAX_HP_RANGED_ATTACK_PENALTY = json.MAX_HP_RANGED_ATTACK_PENALTY;
    this.MAX_HP_MELEE_ATTACK_BONUS = json.MAX_HP_MELEE_ATTACK_BONUS;
    this.MAX_HP_MELEE_ATTACK_PENALTY = json.MAX_HP_MELEE_ATTACK_PENALTY;
    this.MAX_DAMAGE_MODIFIER_CLAMP = json.MAX_DAMAGE_MODIFIER_CLAMP;
    this.NEARBY_UNITS_DISTANCE = json.NEARBY_UNITS_DISTANCE;
    this.NEARBY_UNITS_CHARGE_RESISTANCE_MODIFIER_CAP =
      json.NEARBY_UNITS_CHARGE_RESISTANCE_MODIFIER_CAP;
    this.NEARBY_UNITS_CHARGE_RESISTANCE_MODIFIER_PENALTY_CAP =
      json.NEARBY_UNITS_CHARGE_RESISTANCE_MODIFIER_PENALTY_CAP;
    this.NEARBY_UNITS_CHARGE_PENETRATION_MODIFIER_CAP =
      json.NEARBY_UNITS_CHARGE_PENETRATION_MODIFIER_CAP;
    this.NEARBY_UNITS_CHARGE_PENETRATION_MODIFIER_PENALTY_CAP =
      json.NEARBY_UNITS_CHARGE_PENETRATION_MODIFIER_PENALTY_CAP;
    this.MIN_EFFECTIVE_VPS = json.MIN_EFFECTIVE_VPS;
    this.SHOT_TRAJECTORY_TARGET_ALTITUDE = json.SHOT_TRAJECTORY_TARGET_ALTITUDE;
    this.OFFER_DRAW_COOLDOWN = json.OFFER_DRAW_COOLDOWN;
    this.MAX_ENTITY_NAME_LENGTH = json.MAX_ENTITY_NAME_LENGTH;
    this.CHARGE_BACKLASH_RESIST_MOD = json.CHARGE_BACKLASH_RESIST_MOD;
    this.CHARGE_BACKLASH_MAX_REDUCTION = json.CHARGE_BACKLASH_MAX_REDUCTION;
    this.CHARGE_BACKLASH_DEFENDER_CHARGE_BONUS_MULTIPLIER =
      json.CHARGE_BACKLASH_DEFENDER_CHARGE_BONUS_MULTIPLIER;
    this.CHARGE_BACKLASH_DEFENDER_RESISTANCE_MULTIPLIER =
      json.CHARGE_BACKLASH_DEFENDER_RESISTANCE_MULTIPLIER;
    this.HAS_TAKEN_FIRE_SPEED_MODIFIER = json.HAS_TAKEN_FIRE_SPEED_MODIFIER;
    this.EFFECT_HAS_RAN_TICKS = json.EFFECT_HAS_RAN_TICKS;
    this.EFFECT_STARTED_ROUTING_TICKS = json.EFFECT_STARTED_ROUTING_TICKS;
    this.HEAD_ON_COLLISION_ANGLE_DEGREES = json.HEAD_ON_COLLISION_ANGLE_DEGREES;
    this.HEIGHT_CHANGE_TICKS = json.HEIGHT_CHANGE_TICKS;
    this.WALKING_STAMINA_REGAIN_MODIFIER = json.WALKING_STAMINA_REGAIN_MODIFIER;
    this.FORWARD_DEPLOYMENT_ZONE_OFFSET = json.FORWARD_DEPLOYMENT_ZONE_OFFSET;
    this.FOW_EYE_HEIGHT = json.FOW_EYE_HEIGHT;
    this.FOW_TARGET_HEIGHT = json.FOW_TARGET_HEIGHT;
    this.FOW_LEVEL_0_DISTANCE = json.FOW_LEVEL_0_DISTANCE;
    this.FOW_LEVEL_1_DISTANCE = json.FOW_LEVEL_1_DISTANCE;
    this.FOW_LEVEL_2_DISTANCE = json.FOW_LEVEL_2_DISTANCE;
    this.FOW_LEVEL_3_DISTANCE = json.FOW_LEVEL_3_DISTANCE;
    this.VP_BASE_POINTS = json.VP_BASE_POINTS;
    this.VP_LOSS_RATIO_POINTS = json.VP_LOSS_RATIO_POINTS;
    this.VP_POINTS_TO_TIE_BREAK = json.VP_POINTS_TO_TIE_BREAK;
    this.VP_BIG_DEFAULT_POINTS = json.VP_BIG_DEFAULT_POINTS;
    this.VP_SMALL_DEFAULT_POINTS = json.VP_SMALL_DEFAULT_POINTS;
    this.VP_TICKS_UNDER_PRESSURE_BASE = json.VP_TICKS_UNDER_PRESSURE_BASE;
    this.PLAYER_EXPERIENCE_BASE = json.PLAYER_EXPERIENCE_BASE;
    this.PLAYER_EXPERIENCE_FACTOR = json.PLAYER_EXPERIENCE_FACTOR;
    this.INITIAL_ELO = json.INITIAL_ELO;
    this.UNKNOWN_UNIT_TYPE = json.UNKNOWN_UNIT_TYPE;
    this.DEFAULT_SCENARIO = json.DEFAULT_SCENARIO;
    this.DEFAULT_BATTLE_TYPE = json.DEFAULT_BATTLE_TYPE;
    this.ROUTING_FORMATION = json.ROUTING_FORMATION;
    this.BETA = json.BETA;

    // Scaled stat-coupled constants
    this.CAN_LEAVE_MAP_MIN_ORG =
      json.CAN_LEAVE_MAP_MIN_ORG * STAT_PRECISION_SCALE;
    this.HEIGHT_CHANGE_STAMINA_COST =
      json.HEIGHT_CHANGE_STAMINA_COST * STAT_PRECISION_SCALE;
    this.HEIGHT_CHANGE_RUNNING_STAMINA_COST =
      json.HEIGHT_CHANGE_RUNNING_STAMINA_COST * STAT_PRECISION_SCALE;
  }
}
